<?php

use Illuminate\Database\Seeder;

class JobsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('jobs')->delete();
        
        \DB::table('jobs')->insert(array (
            0 => 
            array (
                'id' => 13,
                'job_title' => 'cat',
                'job_description' => 'ddf',
                'job_skills' => NULL,
                'job_career_level' => '--Choose Career Level--',
                'job_no_of_position' => '4',
                'job_year_of_experience_min' => 3,
                'job_year_of_experience_max' => 4,
                'featuring_status' => 1,
                'job_salary_min_range' => 0,
                'job_salary_max_range' => 0,
                'job_gender_preference' => 'Male',
                'job_oath_status' => NULL,
                'company_id' => NULL,
                'job_type_id' => NULL,
                'job_shift' => NULL,
                'job_sub_category_id' => 1,
                'city_id' => 1,
                'degree_level_id' => 4,
                'degree_type_id' => 3,
                'specific_degree' => NULL,
                'area_id' => NULL,
                'age_requirement_min' => 18,
                'age_requirement_max' => 32,
                'apply_by' => '2018-12-22',
                'approval_status' => 1,
                'active_status' => 1,
                'created_at' => '2018-11-27 12:00:11',
                'updated_at' => '2018-11-27 12:00:11',
            ),
            1 => 
            array (
                'id' => 15,
                'job_title' => 'hassan',
                'job_description' => 'ssfs',
                'job_skills' => NULL,
                'job_career_level' => '--Choose Career Level--',
                'job_no_of_position' => '3',
                'job_year_of_experience_min' => 3,
                'job_year_of_experience_max' => 15,
                'featuring_status' => NULL,
                'job_salary_min_range' => 5000,
                'job_salary_max_range' => 100000,
                'job_gender_preference' => '--Male--',
                'job_oath_status' => NULL,
                'company_id' => NULL,
                'job_type_id' => NULL,
                'job_shift' => '--Select Job Shift--',
                'job_sub_category_id' => 3,
                'city_id' => 1,
                'degree_level_id' => 4,
                'degree_type_id' => 3,
                'specific_degree' => 'tet',
                'area_id' => NULL,
                'age_requirement_min' => 18,
                'age_requirement_max' => 31,
                'apply_by' => '2019-12-10',
                'approval_status' => 1,
                'active_status' => 1,
                'created_at' => '2018-12-04 10:40:36',
                'updated_at' => '2018-12-04 10:40:36',
            ),
            2 => 
            array (
                'id' => 16,
                'job_title' => 'hyusam',
                'job_description' => 'sd',
                'job_skills' => NULL,
                'job_career_level' => '--Choose Career Level--',
                'job_no_of_position' => '5',
                'job_year_of_experience_min' => 4,
                'job_year_of_experience_max' => 17,
                'featuring_status' => NULL,
                'job_salary_min_range' => 5000,
                'job_salary_max_range' => 1000000,
                'job_gender_preference' => '--Female--',
                'job_oath_status' => NULL,
                'company_id' => NULL,
                'job_type_id' => NULL,
                'job_shift' => '--Select Job Shift--',
                'job_sub_category_id' => 1,
                'city_id' => 1,
                'degree_level_id' => 2,
                'degree_type_id' => 1,
                'specific_degree' => 'specific',
                'area_id' => NULL,
                'age_requirement_min' => 19,
                'age_requirement_max' => 56,
                'apply_by' => '2019-12-18',
                'approval_status' => 1,
                'active_status' => 1,
                'created_at' => '2018-12-04 10:53:00',
                'updated_at' => '2018-12-04 10:53:00',
            ),
            3 => 
            array (
                'id' => 18,
                'job_title' => 'check edit',
                'job_description' => 'cjeck edit',
                'job_skills' => '["s","f","t","y","edit"]',
                'job_career_level' => '--UPDATE--',
                'job_no_of_position' => '5',
                'job_year_of_experience_min' => 4,
                'job_year_of_experience_max' => 17,
                'featuring_status' => NULL,
                'job_salary_min_range' => 5001,
                'job_salary_max_range' => 100001,
                'job_gender_preference' => '--UPDATE--',
                'job_oath_status' => NULL,
                'company_id' => NULL,
                'job_type_id' => NULL,
                'job_shift' => '--UPDATE--',
                'job_sub_category_id' => 2,
                'city_id' => 1,
                'degree_level_id' => 1,
                'degree_type_id' => 2,
                'specific_degree' => 'tet edit',
                'area_id' => NULL,
                'age_requirement_min' => 20,
                'age_requirement_max' => 35,
                'apply_by' => '2018-12-19',
                'approval_status' => 0,
                'active_status' => 0,
                'created_at' => '2018-12-05 10:28:04',
                'updated_at' => '2018-12-05 10:28:04',
            ),
            4 => 
            array (
                'id' => 22,
                'job_title' => 'insertion check edit',
                'job_description' => 'insertion check edit',
                'job_skills' => '["insertion check","fd","dd","sdf","edit"]',
                'job_career_level' => 'Intern/Student',
                'job_no_of_position' => '6',
                'job_year_of_experience_min' => 3,
                'job_year_of_experience_max' => 5,
                'featuring_status' => NULL,
                'job_salary_min_range' => 50004,
                'job_salary_max_range' => 100006,
                'job_gender_preference' => 'Female',
                'job_oath_status' => NULL,
                'company_id' => NULL,
                'job_type_id' => 3,
            'job_shift' => 'First Shift(Day)',
                'job_sub_category_id' => 1,
                'city_id' => 1,
                'degree_level_id' => 3,
                'degree_type_id' => NULL,
                'specific_degree' => 'specific degree edit',
                'area_id' => NULL,
                'age_requirement_min' => 24,
                'age_requirement_max' => 26,
                'apply_by' => '2019-12-21',
                'approval_status' => 0,
                'active_status' => 0,
                'created_at' => '2018-12-08 09:50:09',
                'updated_at' => '2018-12-08 09:53:46',
            ),
        ));
        
        
    }
}