<?php

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 3,
                'order_status' => 1,
                'shipper_id' => 57,
                'biller_id' => 65,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '100',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 09:45:01',
                'updated_at' => '2018-10-16 09:45:01',
            ),
            1 => 
            array (
                'id' => 4,
                'order_status' => 0,
                'shipper_id' => 58,
                'biller_id' => 66,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '100',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 10:30:55',
                'updated_at' => '2018-10-16 10:30:55',
            ),
            2 => 
            array (
                'id' => 5,
                'order_status' => 0,
                'shipper_id' => 59,
                'biller_id' => 67,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '100',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 10:31:30',
                'updated_at' => '2018-10-16 10:31:30',
            ),
            3 => 
            array (
                'id' => 6,
                'order_status' => 0,
                'shipper_id' => 60,
                'biller_id' => 68,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '100',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 10:43:55',
                'updated_at' => '2018-10-16 10:43:55',
            ),
            4 => 
            array (
                'id' => 7,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:46:09',
                'updated_at' => '2018-10-16 12:46:09',
            ),
            5 => 
            array (
                'id' => 8,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:46:36',
                'updated_at' => '2018-10-16 12:46:36',
            ),
            6 => 
            array (
                'id' => 9,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:47:14',
                'updated_at' => '2018-10-16 12:47:14',
            ),
            7 => 
            array (
                'id' => 10,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:49:42',
                'updated_at' => '2018-10-16 12:49:42',
            ),
            8 => 
            array (
                'id' => 11,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:50:53',
                'updated_at' => '2018-10-16 12:50:53',
            ),
            9 => 
            array (
                'id' => 12,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:50:53',
                'updated_at' => '2018-10-16 12:50:53',
            ),
            10 => 
            array (
                'id' => 13,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:50:53',
                'updated_at' => '2018-10-16 12:50:53',
            ),
            11 => 
            array (
                'id' => 14,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:54:31',
                'updated_at' => '2018-10-16 12:54:31',
            ),
            12 => 
            array (
                'id' => 15,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:56:02',
                'updated_at' => '2018-10-16 12:56:02',
            ),
            13 => 
            array (
                'id' => 16,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:56:43',
                'updated_at' => '2018-10-16 12:56:43',
            ),
            14 => 
            array (
                'id' => 17,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:58:24',
                'updated_at' => '2018-10-16 12:58:24',
            ),
            15 => 
            array (
                'id' => 18,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:58:50',
                'updated_at' => '2018-10-16 12:58:50',
            ),
            16 => 
            array (
                'id' => 19,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 12:59:28',
                'updated_at' => '2018-10-16 12:59:28',
            ),
            17 => 
            array (
                'id' => 20,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:02:11',
                'updated_at' => '2018-10-16 13:02:11',
            ),
            18 => 
            array (
                'id' => 21,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:02:30',
                'updated_at' => '2018-10-16 13:02:30',
            ),
            19 => 
            array (
                'id' => 22,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:03:17',
                'updated_at' => '2018-10-16 13:03:17',
            ),
            20 => 
            array (
                'id' => 23,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:03:19',
                'updated_at' => '2018-10-16 13:03:19',
            ),
            21 => 
            array (
                'id' => 24,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:03:48',
                'updated_at' => '2018-10-16 13:03:48',
            ),
            22 => 
            array (
                'id' => 25,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:04:22',
                'updated_at' => '2018-10-16 13:04:22',
            ),
            23 => 
            array (
                'id' => 26,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:04:24',
                'updated_at' => '2018-10-16 13:04:24',
            ),
            24 => 
            array (
                'id' => 27,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:05:02',
                'updated_at' => '2018-10-16 13:05:02',
            ),
            25 => 
            array (
                'id' => 28,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:05:03',
                'updated_at' => '2018-10-16 13:05:03',
            ),
            26 => 
            array (
                'id' => 29,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:16:00',
                'updated_at' => '2018-10-16 13:16:00',
            ),
            27 => 
            array (
                'id' => 30,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:16:18',
                'updated_at' => '2018-10-16 13:16:18',
            ),
            28 => 
            array (
                'id' => 31,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:16:52',
                'updated_at' => '2018-10-16 13:16:52',
            ),
            29 => 
            array (
                'id' => 32,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:17:58',
                'updated_at' => '2018-10-16 13:17:58',
            ),
            30 => 
            array (
                'id' => 33,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:18:03',
                'updated_at' => '2018-10-16 13:18:03',
            ),
            31 => 
            array (
                'id' => 34,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:18:28',
                'updated_at' => '2018-10-16 13:18:28',
            ),
            32 => 
            array (
                'id' => 35,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:18:50',
                'updated_at' => '2018-10-16 13:18:50',
            ),
            33 => 
            array (
                'id' => 36,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:19:06',
                'updated_at' => '2018-10-16 13:19:06',
            ),
            34 => 
            array (
                'id' => 37,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:19:20',
                'updated_at' => '2018-10-16 13:19:20',
            ),
            35 => 
            array (
                'id' => 38,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:20:31',
                'updated_at' => '2018-10-16 13:20:31',
            ),
            36 => 
            array (
                'id' => 39,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:20:45',
                'updated_at' => '2018-10-16 13:20:45',
            ),
            37 => 
            array (
                'id' => 40,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:22:17',
                'updated_at' => '2018-10-16 13:22:17',
            ),
            38 => 
            array (
                'id' => 41,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:22:34',
                'updated_at' => '2018-10-16 13:22:34',
            ),
            39 => 
            array (
                'id' => 42,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:24:18',
                'updated_at' => '2018-10-16 13:24:18',
            ),
            40 => 
            array (
                'id' => 43,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:32:13',
                'updated_at' => '2018-10-16 13:32:13',
            ),
            41 => 
            array (
                'id' => 44,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:32:32',
                'updated_at' => '2018-10-16 13:32:32',
            ),
            42 => 
            array (
                'id' => 45,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-16 13:53:10',
                'updated_at' => '2018-10-16 13:53:10',
            ),
            43 => 
            array (
                'id' => 46,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-17 07:55:25',
                'updated_at' => '2018-10-17 07:55:25',
            ),
            44 => 
            array (
                'id' => 47,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-17 09:45:41',
                'updated_at' => '2018-10-17 09:45:41',
            ),
            45 => 
            array (
                'id' => 48,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-17 09:49:26',
                'updated_at' => '2018-10-17 09:49:26',
            ),
            46 => 
            array (
                'id' => 49,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-17 09:50:25',
                'updated_at' => '2018-10-17 09:50:25',
            ),
            47 => 
            array (
                'id' => 50,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-17 09:50:47',
                'updated_at' => '2018-10-17 09:50:47',
            ),
            48 => 
            array (
                'id' => 51,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-17 09:58:54',
                'updated_at' => '2018-10-17 09:58:54',
            ),
            49 => 
            array (
                'id' => 52,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-17 09:59:22',
                'updated_at' => '2018-10-17 09:59:22',
            ),
            50 => 
            array (
                'id' => 53,
                'order_status' => 0,
                'shipper_id' => 1,
                'biller_id' => 1,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-17 10:03:04',
                'updated_at' => '2018-10-17 10:03:04',
            ),
            51 => 
            array (
                'id' => 54,
                'order_status' => 0,
                'shipper_id' => 76,
                'biller_id' => 84,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '4005.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-10-17 11:02:10',
                'updated_at' => '2018-10-17 11:02:10',
            ),
            52 => 
            array (
                'id' => 55,
                'order_status' => 0,
                'shipper_id' => 87,
                'biller_id' => 95,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '106800.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-11-01 05:53:20',
                'updated_at' => '2018-11-01 05:53:20',
            ),
            53 => 
            array (
                'id' => 56,
                'order_status' => 0,
                'shipper_id' => 89,
                'biller_id' => 97,
                'shipping_charges' => '100',
                'order_tax' => '100',
                'order_amount_receivable' => '142400.00',
                'payment_method' => '',
                'user_id' => NULL,
                'discount_id' => 1,
                'created_at' => '2018-11-06 07:43:31',
                'updated_at' => '2018-11-06 07:43:31',
            ),
        ));
        
        
    }
}