<?php

use Illuminate\Database\Seeder;

class ShippingDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('shipping_details')->delete();
        
        \DB::table('shipping_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassan@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'jcjdcdcbhd',
                'created_at' => '2018-10-09 11:54:29',
                'updated_at' => '2018-10-09 11:54:29',
            ),
            1 => 
            array (
                'id' => 2,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'vnjfnvj',
                'created_at' => '2018-10-09 12:29:57',
                'updated_at' => '2018-10-09 12:29:57',
            ),
            2 => 
            array (
                'id' => 3,
                'shipper_first_name' => 'test7',
                'shipper_last_name' => 'test7',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-09 12:56:46',
                'updated_at' => '2018-10-09 12:56:46',
            ),
            3 => 
            array (
                'id' => 4,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 06:00:15',
                'updated_at' => '2018-10-10 06:00:15',
            ),
            4 => 
            array (
                'id' => 5,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 06:01:27',
                'updated_at' => '2018-10-10 06:01:27',
            ),
            5 => 
            array (
                'id' => 6,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 06:35:51',
                'updated_at' => '2018-10-10 06:35:51',
            ),
            6 => 
            array (
                'id' => 7,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 07:18:57',
                'updated_at' => '2018-10-10 07:18:57',
            ),
            7 => 
            array (
                'id' => 8,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 07:20:13',
                'updated_at' => '2018-10-10 07:20:13',
            ),
            8 => 
            array (
                'id' => 9,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 07:25:42',
                'updated_at' => '2018-10-10 07:25:42',
            ),
            9 => 
            array (
                'id' => 10,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 07:30:24',
                'updated_at' => '2018-10-10 07:30:24',
            ),
            10 => 
            array (
                'id' => 11,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 07:36:17',
                'updated_at' => '2018-10-10 07:36:17',
            ),
            11 => 
            array (
                'id' => 12,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 07:44:40',
                'updated_at' => '2018-10-10 07:44:40',
            ),
            12 => 
            array (
                'id' => 13,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 09:29:57',
                'updated_at' => '2018-10-10 09:29:57',
            ),
            13 => 
            array (
                'id' => 14,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 09:54:11',
                'updated_at' => '2018-10-10 09:54:11',
            ),
            14 => 
            array (
                'id' => 15,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 10:09:00',
                'updated_at' => '2018-10-10 10:09:00',
            ),
            15 => 
            array (
                'id' => 16,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 10:11:19',
                'updated_at' => '2018-10-10 10:11:19',
            ),
            16 => 
            array (
                'id' => 17,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 10:16:17',
                'updated_at' => '2018-10-10 10:16:17',
            ),
            17 => 
            array (
                'id' => 18,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 10:18:44',
                'updated_at' => '2018-10-10 10:18:44',
            ),
            18 => 
            array (
                'id' => 19,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 10:22:44',
                'updated_at' => '2018-10-10 10:22:44',
            ),
            19 => 
            array (
                'id' => 20,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 10:46:39',
                'updated_at' => '2018-10-10 10:46:39',
            ),
            20 => 
            array (
                'id' => 21,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'jhhjbh',
                'created_at' => '2018-10-10 11:12:26',
                'updated_at' => '2018-10-10 11:12:26',
            ),
            21 => 
            array (
                'id' => 22,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'jb',
                'created_at' => '2018-10-10 12:00:01',
                'updated_at' => '2018-10-10 12:00:01',
            ),
            22 => 
            array (
                'id' => 23,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 12:02:40',
                'updated_at' => '2018-10-10 12:02:40',
            ),
            23 => 
            array (
                'id' => 24,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 12:15:20',
                'updated_at' => '2018-10-10 12:15:20',
            ),
            24 => 
            array (
                'id' => 25,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 12:18:27',
                'updated_at' => '2018-10-10 12:18:27',
            ),
            25 => 
            array (
                'id' => 26,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 12:58:14',
                'updated_at' => '2018-10-10 12:58:14',
            ),
            26 => 
            array (
                'id' => 27,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 12:59:41',
                'updated_at' => '2018-10-10 12:59:41',
            ),
            27 => 
            array (
                'id' => 28,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 13:00:07',
                'updated_at' => '2018-10-10 13:00:07',
            ),
            28 => 
            array (
                'id' => 29,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 13:00:45',
                'updated_at' => '2018-10-10 13:00:45',
            ),
            29 => 
            array (
                'id' => 30,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 13:01:04',
                'updated_at' => '2018-10-10 13:01:04',
            ),
            30 => 
            array (
                'id' => 31,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-10 13:01:36',
                'updated_at' => '2018-10-10 13:01:36',
            ),
            31 => 
            array (
                'id' => 32,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 07:34:59',
                'updated_at' => '2018-10-12 07:34:59',
            ),
            32 => 
            array (
                'id' => 33,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 07:36:29',
                'updated_at' => '2018-10-12 07:36:29',
            ),
            33 => 
            array (
                'id' => 34,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 07:37:12',
                'updated_at' => '2018-10-12 07:37:12',
            ),
            34 => 
            array (
                'id' => 35,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 07:40:36',
                'updated_at' => '2018-10-12 07:40:36',
            ),
            35 => 
            array (
                'id' => 36,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 10:39:07',
                'updated_at' => '2018-10-12 10:39:07',
            ),
            36 => 
            array (
                'id' => 37,
                'shipper_first_name' => 'testt',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 11:02:21',
                'updated_at' => '2018-10-12 11:02:21',
            ),
            37 => 
            array (
                'id' => 38,
                'shipper_first_name' => 'testt',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 11:18:08',
                'updated_at' => '2018-10-12 11:18:08',
            ),
            38 => 
            array (
                'id' => 39,
                'shipper_first_name' => 'test',
                'shipper_last_name' => 'test',
                'shipper_email' => 'test@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 11:43:05',
                'updated_at' => '2018-10-12 11:43:05',
            ),
            39 => 
            array (
                'id' => 40,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 12:54:43',
                'updated_at' => '2018-10-12 12:54:43',
            ),
            40 => 
            array (
                'id' => 41,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 12:56:24',
                'updated_at' => '2018-10-12 12:56:24',
            ),
            41 => 
            array (
                'id' => 42,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 12:58:12',
                'updated_at' => '2018-10-12 12:58:12',
            ),
            42 => 
            array (
                'id' => 43,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'lahore',
                'created_at' => '2018-10-12 12:58:17',
                'updated_at' => '2018-10-12 12:58:17',
            ),
            43 => 
            array (
                'id' => 44,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 06:46:55',
                'updated_at' => '2018-10-16 06:46:55',
            ),
            44 => 
            array (
                'id' => 45,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 07:15:54',
                'updated_at' => '2018-10-16 07:15:54',
            ),
            45 => 
            array (
                'id' => 46,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 07:17:02',
                'updated_at' => '2018-10-16 07:17:02',
            ),
            46 => 
            array (
                'id' => 47,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 07:36:26',
                'updated_at' => '2018-10-16 07:36:26',
            ),
            47 => 
            array (
                'id' => 48,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 07:38:41',
                'updated_at' => '2018-10-16 07:38:41',
            ),
            48 => 
            array (
                'id' => 49,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 07:40:34',
                'updated_at' => '2018-10-16 07:40:34',
            ),
            49 => 
            array (
                'id' => 50,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 07:40:59',
                'updated_at' => '2018-10-16 07:40:59',
            ),
            50 => 
            array (
                'id' => 51,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 07:43:00',
                'updated_at' => '2018-10-16 07:43:00',
            ),
            51 => 
            array (
                'id' => 52,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 07:44:03',
                'updated_at' => '2018-10-16 07:44:03',
            ),
            52 => 
            array (
                'id' => 53,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 09:40:59',
                'updated_at' => '2018-10-16 09:40:59',
            ),
            53 => 
            array (
                'id' => 54,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 09:42:19',
                'updated_at' => '2018-10-16 09:42:19',
            ),
            54 => 
            array (
                'id' => 55,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 09:43:55',
                'updated_at' => '2018-10-16 09:43:55',
            ),
            55 => 
            array (
                'id' => 56,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 09:44:20',
                'updated_at' => '2018-10-16 09:44:20',
            ),
            56 => 
            array (
                'id' => 57,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 09:45:01',
                'updated_at' => '2018-10-16 09:45:01',
            ),
            57 => 
            array (
                'id' => 58,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 10:30:55',
                'updated_at' => '2018-10-16 10:30:55',
            ),
            58 => 
            array (
                'id' => 59,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 10:31:30',
                'updated_at' => '2018-10-16 10:31:30',
            ),
            59 => 
            array (
                'id' => 60,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 10:43:55',
                'updated_at' => '2018-10-16 10:43:55',
            ),
            60 => 
            array (
                'id' => 61,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 10:49:04',
                'updated_at' => '2018-10-16 10:49:04',
            ),
            61 => 
            array (
                'id' => 62,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 11:16:29',
                'updated_at' => '2018-10-16 11:16:29',
            ),
            62 => 
            array (
                'id' => 63,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 11:17:36',
                'updated_at' => '2018-10-16 11:17:36',
            ),
            63 => 
            array (
                'id' => 64,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 11:19:57',
                'updated_at' => '2018-10-16 11:19:57',
            ),
            64 => 
            array (
                'id' => 65,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 11:26:10',
                'updated_at' => '2018-10-16 11:26:10',
            ),
            65 => 
            array (
                'id' => 66,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 11:52:05',
                'updated_at' => '2018-10-16 11:52:05',
            ),
            66 => 
            array (
                'id' => 67,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 12:42:52',
                'updated_at' => '2018-10-16 12:42:52',
            ),
            67 => 
            array (
                'id' => 68,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 12:45:00',
                'updated_at' => '2018-10-16 12:45:00',
            ),
            68 => 
            array (
                'id' => 69,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 12:45:27',
                'updated_at' => '2018-10-16 12:45:27',
            ),
            69 => 
            array (
                'id' => 70,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-16 12:45:47',
                'updated_at' => '2018-10-16 12:45:47',
            ),
            70 => 
            array (
                'id' => 71,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-17 07:24:59',
                'updated_at' => '2018-10-17 07:24:59',
            ),
            71 => 
            array (
                'id' => 72,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-17 07:26:22',
                'updated_at' => '2018-10-17 07:26:22',
            ),
            72 => 
            array (
                'id' => 73,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore 1',
                'created_at' => '2018-10-17 07:39:31',
                'updated_at' => '2018-10-17 07:39:31',
            ),
            73 => 
            array (
                'id' => 74,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-17 09:40:43',
                'updated_at' => '2018-10-17 09:40:43',
            ),
            74 => 
            array (
                'id' => 75,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-17 09:43:58',
                'updated_at' => '2018-10-17 09:43:58',
            ),
            75 => 
            array (
                'id' => 76,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore
',
                'created_at' => '2018-10-17 11:02:10',
                'updated_at' => '2018-10-17 11:02:10',
            ),
            76 => 
            array (
                'id' => 77,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 12:43:56',
                'updated_at' => '2018-10-18 12:43:56',
            ),
            77 => 
            array (
                'id' => 78,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 12:52:36',
                'updated_at' => '2018-10-18 12:52:36',
            ),
            78 => 
            array (
                'id' => 79,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 12:57:33',
                'updated_at' => '2018-10-18 12:57:33',
            ),
            79 => 
            array (
                'id' => 80,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 13:17:36',
                'updated_at' => '2018-10-18 13:17:36',
            ),
            80 => 
            array (
                'id' => 81,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 13:20:50',
                'updated_at' => '2018-10-18 13:20:50',
            ),
            81 => 
            array (
                'id' => 82,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 13:21:34',
                'updated_at' => '2018-10-18 13:21:34',
            ),
            82 => 
            array (
                'id' => 83,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 13:25:09',
                'updated_at' => '2018-10-18 13:25:09',
            ),
            83 => 
            array (
                'id' => 84,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 13:25:42',
                'updated_at' => '2018-10-18 13:25:42',
            ),
            84 => 
            array (
                'id' => 85,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 13:26:15',
                'updated_at' => '2018-10-18 13:26:15',
            ),
            85 => 
            array (
                'id' => 86,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore',
                'created_at' => '2018-10-18 13:26:44',
                'updated_at' => '2018-10-18 13:26:44',
            ),
            86 => 
            array (
                'id' => 87,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore
',
                'created_at' => '2018-11-01 05:53:20',
                'updated_at' => '2018-11-01 05:53:20',
            ),
            87 => 
            array (
                'id' => 88,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore
',
                'created_at' => '2018-11-01 13:24:45',
                'updated_at' => '2018-11-01 13:24:45',
            ),
            88 => 
            array (
                'id' => 89,
                'shipper_first_name' => 'hassan',
                'shipper_last_name' => 'zaidi',
                'shipper_email' => 'hassanzaidi20@gmail.com',
                'shipper_phone_number' => '03224289656',
                'city_id' => 1,
                'shipper_address' => 'Lahore
',
                'created_at' => '2018-11-06 07:43:31',
                'updated_at' => '2018-11-06 07:43:31',
            ),
        ));
        
        
    }
}