<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'first_name' => 'hassan',
                'last_name' => 'zaidi',
                'email' => 'hassan@gmail.com',
                'password' => '123456',
                'address' => 'Lahore',
                'cnic' => NULL,
                'contact_number' => '03224289656',
                'date_of_birth' => NULL,
                'gender' => 'Male',
                'nationality' => NULL,
                'profile_pic' => NULL,
                'profile_url' => NULL,
                'profile_pic_size' => NULL,
                'profile_pic_extension' => NULL,
                'area_id' => NULL,
                'city_id' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'activation' => 1,
                'remember_token' => NULL,
                'verified' => 0,
                'created_at' => '2018-09-05 16:23:11',
                'updated_at' => '2018-09-05 16:23:11',
            ),
            1 => 
            array (
                'id' => 2,
                'first_name' => 'moazzam',
                'last_name' => 'rafique',
                'email' => 'm@gmail.com',
                'password' => '123456',
                'address' => NULL,
                'cnic' => NULL,
                'contact_number' => NULL,
                'date_of_birth' => NULL,
                'gender' => NULL,
                'nationality' => NULL,
                'profile_pic' => NULL,
                'profile_url' => NULL,
                'profile_pic_size' => NULL,
                'profile_pic_extension' => NULL,
                'area_id' => NULL,
                'city_id' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'activation' => 1,
                'remember_token' => NULL,
                'verified' => 0,
                'created_at' => '2018-09-05 17:22:44',
                'updated_at' => '2018-09-05 17:22:44',
            ),
            2 => 
            array (
                'id' => 4,
                'first_name' => 'ali',
                'last_name' => 'usman',
                'email' => 'ali@gmail.com',
                'password' => '$2y$10$0OsN/uOZuJD.S9hws2wCNey6yHrkI97rBirL3fyowp1/5.MxvIgXm',
                'address' => NULL,
                'cnic' => NULL,
                'contact_number' => NULL,
                'date_of_birth' => NULL,
                'gender' => NULL,
                'nationality' => NULL,
                'profile_pic' => NULL,
                'profile_url' => NULL,
                'profile_pic_size' => NULL,
                'profile_pic_extension' => NULL,
                'area_id' => NULL,
                'city_id' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'activation' => 1,
                'remember_token' => NULL,
                'verified' => 0,
                'created_at' => '2018-09-05 18:54:37',
                'updated_at' => '2018-09-05 18:54:37',
            ),
            3 => 
            array (
                'id' => 5,
                'first_name' => 'bilal',
                'last_name' => 'usman',
                'email' => 'bi@gmail.com',
                'password' => '$2y$10$IBddtGgwgy4gA0XZh1Aqk.OX.o/FCkbr3Qw1AmEmC5pClEytJKbuG',
                'address' => NULL,
                'cnic' => NULL,
                'contact_number' => NULL,
                'date_of_birth' => NULL,
                'gender' => NULL,
                'nationality' => NULL,
                'profile_pic' => NULL,
                'profile_url' => NULL,
                'profile_pic_size' => NULL,
                'profile_pic_extension' => NULL,
                'area_id' => NULL,
                'city_id' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'activation' => 1,
                'remember_token' => NULL,
                'verified' => 0,
                'created_at' => '2018-09-19 06:31:48',
                'updated_at' => '2018-09-19 06:31:48',
            ),
            4 => 
            array (
                'id' => 6,
                'first_name' => 'hassan',
                'last_name' => 'zaidi',
                'email' => 'hassanzaidi20@gmail.com',
                'password' => '$2y$10$ndSZQbidGS6z0FSqErjEPetwUJ7s/zuLdxcn2wlMzNo8EosG4xjle',
                'address' => 'Lahore',
                'cnic' => NULL,
                'contact_number' => '03224289656',
                'date_of_birth' => NULL,
                'gender' => NULL,
                'nationality' => NULL,
                'profile_pic' => NULL,
                'profile_url' => NULL,
                'profile_pic_size' => NULL,
                'profile_pic_extension' => NULL,
                'area_id' => NULL,
                'city_id' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'activation' => 1,
                'remember_token' => 'CRIGlPFc6JICiZ4A3fr9XJyDmpd426a8vKym7OpfzQtZeFvLNkhqatPuX5y2',
                'verified' => 0,
                'created_at' => '2018-10-04 13:18:28',
                'updated_at' => '2018-10-04 13:18:28',
            ),
            5 => 
            array (
                'id' => 7,
                'first_name' => 'Hussam',
                'last_name' => 'Azhar',
                'email' => 'hsmkiller16@gmail.com',
                'password' => '$2y$10$qEsYXMTyFv/BybRxdYCfIeK22U22L11S0zREBsBc8g2bZlen73kUS',
                'address' => NULL,
                'cnic' => '35454564564',
                'contact_number' => '3074572916',
                'date_of_birth' => '1994-09-16',
                'gender' => 'Male',
                'nationality' => 'pakistan',
                'profile_pic' => NULL,
                'profile_url' => NULL,
                'profile_pic_size' => NULL,
                'profile_pic_extension' => NULL,
                'area_id' => NULL,
                'city_id' => 1,
                'provider' => NULL,
                'provider_id' => NULL,
                'activation' => 1,
                'remember_token' => '3kT4qJQ2efhNDw2UznSBXgp6eUbTr4PuLoeWoAfKLkHymk17fNjBdCNsUAIj',
                'verified' => 1,
                'created_at' => '2018-12-17 05:59:51',
                'updated_at' => '2018-12-20 08:08:54',
            ),
            6 => 
            array (
                'id' => 8,
                'first_name' => 'Hassam',
                'last_name' => 'Azhar',
                'email' => 'hussam.ravian16@gmail.com',
                'password' => '$2y$10$NIvAEF/o6JwA7.9/oMWDY.Ep.QfNtq4ASWnHKmHjG6OS3gNO5d8z2',
                'address' => NULL,
                'cnic' => NULL,
                'contact_number' => NULL,
                'date_of_birth' => '1994-09-16',
                'gender' => 'Male',
                'nationality' => NULL,
                'profile_pic' => NULL,
                'profile_url' => NULL,
                'profile_pic_size' => NULL,
                'profile_pic_extension' => NULL,
                'area_id' => NULL,
                'city_id' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'activation' => 1,
                'remember_token' => '010qsb7K2wApSERebQe9m3O3vZ5fcRWo3GKSefUF48luQ3nHe4qjVLsUAfpI',
                'verified' => 1,
                'created_at' => '2019-01-10 13:22:11',
                'updated_at' => '2019-01-10 13:22:11',
            ),
            7 => 
            array (
                'id' => 9,
                'first_name' => 'Moazzam',
                'last_name' => 'Rafique',
                'email' => 'ilovepakistan811@gmail.com',
                'password' => '$2y$10$FBjw1f0IpYdvLx4GskHmTOGn9tbBjhRmVVCNOBungz50qAmjySzm.',
                'address' => NULL,
                'cnic' => NULL,
                'contact_number' => NULL,
                'date_of_birth' => NULL,
                'gender' => NULL,
                'nationality' => NULL,
                'profile_pic' => NULL,
                'profile_url' => NULL,
                'profile_pic_size' => NULL,
                'profile_pic_extension' => NULL,
                'area_id' => NULL,
                'city_id' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'activation' => 1,
                'remember_token' => 'bQwBKKaA7GdqJ5XNBfAA4RXEDQ8BciKxkJmrcGBL9rpg02GLtHUxE9IjMByV',
                'verified' => 1,
                'created_at' => '2019-02-18 05:44:29',
                'updated_at' => '2019-02-18 05:45:06',
            ),
            8 => 
            array (
                'id' => 10,
                'first_name' => 'super',
                'last_name' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => '$2y$10$6c4GO7psrGlFyBc7DQFt..FGlvYkB3LIMBnk3cJw53y4TEcMuuoTK',
                'address' => NULL,
                'cnic' => NULL,
                'contact_number' => NULL,
                'date_of_birth' => NULL,
                'gender' => NULL,
                'nationality' => NULL,
                'profile_pic' => NULL,
                'profile_url' => NULL,
                'profile_pic_size' => NULL,
                'profile_pic_extension' => NULL,
                'area_id' => NULL,
                'city_id' => NULL,
                'provider' => NULL,
                'provider_id' => NULL,
                'activation' => 1,
                'remember_token' => '3k1HzCxdvGIhcdOxKeYqzY9jnjwEk7HBvWZl7RC1pvrNJNgw2sFantn9jch2',
                'verified' => 1,
                'created_at' => '2019-02-18 05:55:41',
                'updated_at' => '2019-02-18 05:55:47',
            ),
        ));
        
        
    }
}